# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitdepart', '0002_problemdepart_resolved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemdepart',
            options={},
        ),
    ]
