# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20171225_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helparticle',
            old_name='sutitle',
            new_name='subtitle',
        ),
    ]
