# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_auto_20171225_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helparticle',
            name='is_pdf',
            field=models.BooleanField(default=True),
        ),
    ]
