# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_auto_20171225_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helparticle',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Description rapide'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Titre'),
        ),
    ]
