# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_auto_20171225_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre de paragraphe')),
                ('subtitle', models.TextField(verbose_name='Texte')),
            ],
        ),
        migrations.AlterModelOptions(
            name='helparticle',
            options={'ordering': ('title',)},
        ),
    ]
