# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_auto_20171226_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpparagraph',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='help.HelpArticle'),
            preserve_default=False,
        ),
    ]
