# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='all_binets_passed',
            field=models.BooleanField(default=False),
        ),
    ]
