# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ('-nom',)},
        ),
        migrations.AlterField(
            model_name='eleve',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Promotion'),
            preserve_default=False,
        ),
    ]
