# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170702_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together=set([('nom',)]),
        ),
    ]
