# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_eleve_signed_fiche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'permissions': (('see_circuitdepart', 'Voir le circuit de départ'),)},
        ),
    ]
