# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('binets', '0019_auto_20171107_2005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('admin_only', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('see_all_comments', 'Voir les commentaires admin'),),
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('take_date', models.DateTimeField(verbose_name='attribuée le')),
                ('close_date', models.DateTimeField(verbose_name='fermée le')),
                ('is_closed', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('due_date', models.DateField(verbose_name='A faire avant le')),
                ('description', models.TextField()),
                ('finisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finisher', to=settings.AUTH_USER_MODEL, verbose_name='fermée par')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Mandat')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL, verbose_name='attribuée à')),
            ],
            options={
                'ordering': ('is_urgent', 'due_date'),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
