# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fermée le'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finisher', to=settings.AUTH_USER_MODEL, verbose_name='fermée par'),
        ),
        migrations.AlterField(
            model_name='task',
            name='take_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='attribuée le'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker', to=settings.AUTH_USER_MODEL, verbose_name='attribuée à'),
        ),
    ]
