# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('is_closed', '-is_urgent', 'due_date')},
        ),
    ]
