# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvention',
            name='debloque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
