# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
        ('subventions', '0003_typesubvention_deblocable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeblocageSubvention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ligne_compta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compta.LigneCompta')),
                ('subvention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subventions.Subvention')),
            ],
        ),
    ]
