# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subventions', '0006_auto_20170720_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesubvention',
            name='deblocable',
            field=models.BooleanField(default=True),
        ),
    ]
