# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subventions', '0007_auto_20170729_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvention',
            name='is_versee',
            field=models.BooleanField(default=False),
        ),
    ]
