# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleveVos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye', models.BooleanField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='MontantCheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.BooleanField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.EleveVos')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paye', models.BooleanField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('-nom',),
            },
        ),
        migrations.CreateModel(
            name='VOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.Section')),
            ],
        ),
        migrations.AddField(
            model_name='remboursement',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.VOS'),
        ),
        migrations.AddField(
            model_name='participation',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.VOS'),
        ),
        migrations.AddField(
            model_name='participation',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Promotion'),
        ),
        migrations.AddField(
            model_name='montantcheque',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.VOS'),
        ),
        migrations.AddField(
            model_name='montantcheque',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Promotion'),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.VOS'),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='montant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.MontantCheque'),
        ),
        migrations.AddField(
            model_name='encaissement',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Promotion'),
        ),
        migrations.AddField(
            model_name='elevevos',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vos.Section'),
        ),
    ]
