# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0004_auto_20170731_0904'),
        ('vos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vos',
            name='binet_ptr',
        ),
        migrations.AddField(
            model_name='vos',
            name='mandat_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='binets.Mandat'),
            preserve_default=False,
        ),
    ]
