# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('remarques_admins', models.TextField(null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCompta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dépense effectuée')),
                ('description', models.CharField(max_length=200)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Eleve')),
                ('binet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Binet')),
            ],
        ),
        migrations.CreateModel(
            name='Mandats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Binet')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Promotion'),
        ),
        migrations.AddField(
            model_name='binet',
            name='type_binet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.TypeBinet'),
        ),
    ]
