# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('binets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCompta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Effectuée le')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='ajoutée le')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('hahaha', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to=settings.AUTH_USER_MODEL, verbose_name='ajoutée par')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Mandat')),
                ('modificateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificateur', to=settings.AUTH_USER_MODEL, verbose_name='modifiée par')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
    ]
