# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandats',
            old_name='president',
            new_name='tresorier',
        ),
    ]
