# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0001_initial'),
        ('compta', '0002_remove_lignecompta_hahaha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subvention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('postes', models.TextField()),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Mandat')),
            ],
            options={
                'ordering': ('vague', 'mandat'),
            },
        ),
        migrations.CreateModel(
            name='TypeSubvention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VagueSubventions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('type_subvention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.TypeSubvention')),
            ],
            options={
                'ordering': ('-annee',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='typesubvention',
            unique_together=set([('nom',)]),
        ),
        migrations.AddField(
            model_name='subvention',
            name='vague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.VagueSubventions'),
        ),
        migrations.AlterUniqueTogether(
            name='vaguesubventions',
            unique_together=set([('type_subvention', 'annee')]),
        ),
        migrations.AlterUniqueTogether(
            name='subvention',
            unique_together=set([('vague', 'mandat')]),
        ),
    ]
