# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0003_auto_20170624_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='binet',
            name='current_promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compta.Promotion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binet',
            name='current_tresorier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compta.Eleve'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lignecompta',
            name='credit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lignecompta',
            name='debit',
            field=models.FloatField(null=True),
        ),
    ]
