# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0003_auto_20170713_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subvention',
            old_name='montant',
            new_name='accorde',
        ),
        migrations.AddField(
            model_name='subvention',
            name='demande',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
