# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0004_auto_20170803_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedepense',
            name='nom',
            field=models.CharField(max_length=15),
        ),
    ]
