# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-29 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0005_auto_20170803_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecompta',
            options={'ordering': ('-date', '-id'), 'permissions': (('validate_polymedia', 'Effectuer des validations Polymédia'),)},
        ),
    ]
