# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compta', '0006_auto_20170624_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='binet',
            name='current_promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Promotion', verbose_name='Promo'),
        ),
        migrations.AlterField(
            model_name='binet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binet',
            name='remarques_admins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignecompta',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.Eleve', verbose_name='Par'),
        ),
        migrations.AlterField(
            model_name='lignecompta',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignecompta',
            name='date',
            field=models.DateField(verbose_name='Effectuée le'),
        ),
        migrations.AlterField(
            model_name='lignecompta',
            name='debit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
