# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0006_auto_20171029_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecompta',
            options={'ordering': ('-date', '-id', '-reference'), 'permissions': (('validate_polymedia', 'Effectuer des validations Polymédia'),)},
        ),
        migrations.AddField(
            model_name='lignecompta',
            name='reference',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
