# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0008_auto_20170702_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binet',
            name='current_president',
        ),
        migrations.RemoveField(
            model_name='binet',
            name='current_promotion',
        ),
        migrations.RemoveField(
            model_name='binet',
            name='current_tresorier',
        ),
        migrations.RemoveField(
            model_name='binet',
            name='type_binet',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='binet',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='president',
        ),
        migrations.RemoveField(
            model_name='mandat',
            name='tresorier',
        ),
        migrations.AlterField(
            model_name='lignecompta',
            name='binet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Binet'),
        ),
        migrations.DeleteModel(
            name='Binet',
        ),
        migrations.DeleteModel(
            name='Mandat',
        ),
        migrations.DeleteModel(
            name='TypeBinet',
        ),
    ]
