# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0008_auto_20171104_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecompta',
            name='reference',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
