# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0009_auto_20171106_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecompta',
            options={'ordering': ('-date', '-reference', '-id'), 'permissions': (('validate_polymedia', 'Effectuer des validations Polymédia'),)},
        ),
    ]
