# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0010_auto_20171107_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecompta',
            name='facture_ok',
            field=models.BooleanField(default=False),
        ),
    ]
