# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0011_lignecompta_facture_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedepense',
            name='previsionnel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
