# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0014_auto_20171201_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedepense',
            name='previsionnel_deblocages',
        ),
    ]
