# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0019_auto_20171107_2005'),
        ('compta', '0015_remove_postedepense_previsionnel_deblocages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('mandat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='binets.Mandat')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='evenement',
            unique_together=set([('nom', 'mandat')]),
        ),
    ]
