# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0017_auto_20171203_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
