# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0021_auto_20171203_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postedepense',
            options={'ordering': ('evenement', 'nom')},
        ),
    ]
