# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0022_auto_20171203_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='ajoutée le')),
            ],
        ),
        migrations.AddField(
            model_name='lignecompta',
            name='hidden_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compta.HiddenOperation'),
        ),
    ]
