# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compta', '0024_auto_20171229_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenOperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poste_depense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compta.PosteDepense')),
            ],
        ),
        migrations.AlterModelOptions(
            name='hiddenoperation',
            options={'ordering': ('-close_date',)},
        ),
        migrations.RenameField(
            model_name='hiddenoperation',
            old_name='date',
            new_name='add_date',
        ),
        migrations.AddField(
            model_name='hiddenoperation',
            name='close_date',
            field=models.DateTimeField(auto_now=True, verbose_name='fermée le'),
        ),
        migrations.AddField(
            model_name='hiddenoperation',
            name='closer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dernier_utilisateur', to=settings.AUTH_USER_MODEL, verbose_name='fermée par'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiddenoperation',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='createur', to=settings.AUTH_USER_MODEL, verbose_name='ajoutée par'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiddenoperation',
            name='operation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compta.HiddenOperationType'),
            preserve_default=False,
        ),
    ]
