# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20170702_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarques_admins', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(verbose_name='Actif')),
                ('current_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_president', to='accounts.Eleve', verbose_name='Président')),
                ('current_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Promotion', verbose_name='Promo')),
                ('current_tresorier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_tresorier', to='accounts.Eleve', verbose_name='Trésorier')),
            ],
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.Binet')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='accounts.Eleve')),
                ('tresorier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tresorier', to='accounts.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='TypeBinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='binet',
            name='type_binet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.TypeBinet', verbose_name='chéquier'),
        ),
    ]
