# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandat',
            name='remarques_admins',
            field=models.TextField(blank=True, null=True),
        ),
    ]
