# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binet',
            options={'ordering': ('current_promotion', 'nom')},
        ),
    ]
