# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0002_auto_20170704_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='binet',
            name='type_binet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binets.TypeBinet', verbose_name='Type du binet'),
        ),
    ]
