# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0003_mandat_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binet',
            options={'ordering': ('nom',)},
        ),
        migrations.RemoveField(
            model_name='binet',
            name='current_president',
        ),
        migrations.RemoveField(
            model_name='binet',
            name='current_promotion',
        ),
        migrations.RemoveField(
            model_name='binet',
            name='current_tresorier',
        ),
        migrations.RemoveField(
            model_name='binet',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='binet',
            name='type_binet',
        ),
    ]
