# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170702_1731'),
        ('binets', '0003_auto_20170705_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Promotion', verbose_name='Promo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='binet',
            unique_together=set([('nom',)]),
        ),
        migrations.AlterUniqueTogether(
            name='typebinet',
            unique_together=set([('nom',)]),
        ),
    ]
