# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0004_auto_20170705_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binet',
            name='current_president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_president', to=settings.AUTH_USER_MODEL, verbose_name='Président'),
        ),
        migrations.AlterField(
            model_name='binet',
            name='current_tresorier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_tresorier', to=settings.AUTH_USER_MODEL, verbose_name='Trésorier'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='tresorier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tresorier', to=settings.AUTH_USER_MODEL),
        ),
    ]
