# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0005_auto_20170804_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='binet',
            name='current_mandat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_mandat', to='binets.Mandat'),
        ),
    ]
