# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170702_1731'),
        ('binets', '0005_auto_20170705_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mandat',
            unique_together=set([('binet', 'promotion')]),
        ),
    ]
