# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('binets', '0006_binet_current_mandat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binet',
            name='current_mandat',
        ),
        migrations.AddField(
            model_name='binet',
            name='current_promotion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_promotion', to='accounts.Promotion'),
        ),
    ]
