# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0009_remove_binet_current_mandat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='is_displayed',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
