# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0010_mandat_is_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandat',
            name='being_checked',
            field=models.BooleanField(default=False, verbose_name='Vérification compta commencée'),
        ),
    ]
