# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0012_auto_20170809_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandat',
            options={'ordering': ('binet', 'promotion'), 'permissions': (('create_binet', 'Créer ou passer un binet'),)},
        ),
    ]
