# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0015_auto_20170810_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='binet',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Caché de la liste officielle'),
        ),
    ]
