# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0016_binet_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='binet',
            name='tag_binet',
            field=models.ManyToManyField(to='binets.TagBinet', verbose_name='Catégories du binet'),
        ),
    ]
