# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0017_auto_20171101_1807'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagbinet',
            unique_together=set([('nom',)]),
        ),
    ]
