# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binets', '0018_auto_20171101_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandat',
            options={'ordering': ('binet', 'promotion'), 'permissions': (('see_all_binets', 'Voir les binets cachés'),)},
        ),
    ]
